spring:
  application:
    name: Blogilf

  datasource:
    url: jdbc:postgresql://localhost:5432/blogDB
    driverClassName: org.postgresql.Driver
    username: amir
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672

  security:
    user:
      name: test
      password: test
