spring:
  application:
    name: Blogilf

  datasource:
    url: jdbc:postgresql://localhost:5432/blogDB
    driverClassName: org.postgresql.Driver
    username: amir
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
